services:
  app:
    image: kooldev/php:8.3-nginx
    ports:
      - "${KOOL_APP_PORT:-80}:80"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  database:
    image: mariadb:10.5
    ports:
      - ${KOOL_DATABASE_PORT:-3306}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD-rootpass}
      MARIADB_DATABASE: ${DB_DATABASE-database}
      MARIADB_USER: ${DB_USERNAME-user}
      MARIADB_PASSWORD: ${DB_PASSWORD-pass}
      MARIADB_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - database:/var/lib/mysql:delegated
      - ./docker/local:/docker-entrypoint-initdb.d
    networks:
      - kool_local
    healthcheck:
      test: mysqladmin -p${DB_PASSWORD-pass} ping
#
# Networks definitions
#
networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
  database:
